apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcatalogueapp
  labels:
    app: foodcatalogueapp
spec:
  selector:
    matchLabels:
      app: foodcatalogueapp
  template:
    metadata:
      labels:
        app: foodcatalogueapp
    spec:
      containers:
      - name: foodcatalogueapp
        image: srikanthkoya/food-catalogue-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: foodcataloguedb_url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: mysql-username
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalogue-service
spec:
  selector:
    app: foodcatalogueapp
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP

