apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
  labels:
    app: orderapp
spec:
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
      - name: orderapp
        image: srikanthkoya/order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9094
        env:
          - name: SPRING_DATA_MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: secret
                key: orderdb_url
          - name: SPRING_DATA_MONGODB_DATABASE
            value: "orderdb"
          - name: JAVA_TOOL_OPTIONS
            value: "-Djdk.tls.client.protocols=TLSv1.2"

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: orderapp
  ports:
  - port: 9094
    targetPort: 9094
    protocol: TCP

